apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::349765874984:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::349765874984:role/eksctl-jwt-api-nodegroup-ng-e6300-NodeInstanceRole-NHQP1NJ8SBPP\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-18T03:56:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3616"
  uid: a33b2bb8-358c-475b-8565-0254778b7270
